// Generated by tools/img2panel.py
#pragma once
#include <stdint.h>

namespace CatArt {
  constexpr int16_t WIDTH  = 189;
  constexpr int16_t HEIGHT = 155;
}

extern const uint8_t CAT_ART_DATA[7440];   // 2 bits/pixel, row stride 48 bytes