[env:esp32dev]
platform = espressif32@6.9.0   ; pin it so Arduino core versions don't shift under you
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps = adafruit/Adafruit GFX Library
build_flags = -I${PROJECT_DIR}/include