#!/usr/bin/env python3
"""
Convert an image to the e-paper panel's 2-bit format and emit a C++ source file.

Panel codes (4 pixels per byte, first pixel in the top bits):
  0 = black, 1 = white, 2 = yellow, 3 = red

Usage:
  python tools/img2panel.py cat.png --name cat --colors bwr --crop-content \
         --out lib/ui/cat_art.cpp --preview cat_preview.png
Options:
  --colors  bw | bwr | bwry     which inks may be used
  --size WxH                    resize (keeps aspect if only W given: --size 189x)
  --crop-content                crop to the non-white/non-transparent bounding box
  --black-point N               luminance (0-255) at or below which neutral greys become solid black
  --white-point N               luminance at or above which neutral greys become solid white
"""
import argparse
import numpy as np
from PIL import Image

# Panel colours as they appear on the display (tune against a photo of your panel).
PANEL = {"black": (25, 25, 25), "white": (230, 230, 220), "yellow": (215, 185, 40), "red": (165, 40, 40)}
CODE = {"black": 0, "white": 1, "yellow": 2, "red": 3}
SETS = {"bw": ["black", "white"], "bwr": ["black", "white", "red"], "bwry": ["black", "white", "red", "yellow"]}


def load_flat(path):
    im = Image.open(path).convert("RGBA")
    bg = Image.new("RGBA", im.size, (255, 255, 255, 255))
    bg.alpha_composite(im)
    return bg.convert("RGB")


def crop_content(im, thresh=720):
    a = np.array(im)
    ys, xs = np.where(a.sum(axis=2) < thresh)
    return im.crop((xs.min(), ys.min(), xs.max() + 1, ys.max() + 1))


def tone_adjust(im, black_pt, white_pt):
    """Push near-neutral greys toward solid black/white so dark areas stay solid; keep colours."""
    a = np.array(im).astype(np.float32)
    lum = a @ np.array([0.299, 0.587, 0.114], dtype=np.float32)
    redness = a[..., 0] - (a[..., 1] + a[..., 2]) / 2
    neutral = redness < 25
    t = np.clip((lum - black_pt) / max(1, white_pt - black_pt), 0, 1)
    new_lum = PANEL["black"][0] + t * (PANEL["white"][0] - PANEL["black"][0])
    out = a.copy()
    for ch in range(3):
        out[..., ch] = np.where(neutral, new_lum, a[..., ch])
    return Image.fromarray(np.clip(out, 0, 255).astype(np.uint8))


def quantize(im, inks):
    pal = [PANEL[n] for n in inks]
    flat = [c for rgb in pal for c in rgb]
    flat += list(pal[0]) * (256 - len(pal))          # pad with a copy of the first ink
    pimg = Image.new("P", (1, 1))
    pimg.putpalette(flat)
    q = np.array(im.quantize(palette=pimg, dither=Image.Dither.FLOYDSTEINBERG))
    q = np.where(q < len(pal), q, 0)                 # padded entries are copies of ink 0
    return q, pal


def pack(idx, inks):
    h, w = idx.shape
    stride = (w + 3) // 4
    out = bytearray(stride * h)
    for y in range(h):
        for x in range(w):
            code = CODE[inks[idx[y, x]]]
            out[y * stride + (x >> 2)] |= code << (6 - 2 * (x & 3))
    return bytes(out), stride


def emit(name, w, h, stride, data, path):
    lines = []
    lines.append(f'// Generated by tools/img2panel.py - do not edit by hand.')
    lines.append(f'#include "{name}_art.h"')
    lines.append('#include <pgmspace.h>')
    lines.append('')
    lines.append(f'const uint8_t {name.upper()}_ART_DATA[{len(data)}] PROGMEM = {{')
    for i in range(0, len(data), 16):
        lines.append('  ' + ', '.join(f'0x{b:02X}' for b in data[i:i + 16]) + ',')
    lines.append('};')
    lines.append('')
    open(path, 'w').write('\n'.join(lines))
    hdr = path[:-4] + '.h' if path.endswith('.cpp') else path + '.h'
    guard = f'{name.upper()}_ART_H'
    open(hdr, 'w').write(
        f'// Generated by tools/img2panel.py\n#pragma once\n#include <stdint.h>\n\n'
        f'namespace {name.capitalize()}Art {{\n'
        f'  constexpr int16_t WIDTH  = {w};\n  constexpr int16_t HEIGHT = {h};\n}}\n\n'
        f'extern const uint8_t {name.upper()}_ART_DATA[{len(data)}];   // 2 bits/pixel, row stride {stride} bytes\n')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('image')
    ap.add_argument('--name', required=True)
    ap.add_argument('--out', required=True)
    ap.add_argument('--colors', default='bwr', choices=SETS.keys())
    ap.add_argument('--size')
    ap.add_argument('--crop-content', action='store_true')
    ap.add_argument('--black-point', type=int, default=70)
    ap.add_argument('--white-point', type=int, default=220)
    ap.add_argument('--preview')
    a = ap.parse_args()

    im = load_flat(a.image)
    if a.crop_content:
        im = crop_content(im)
    if a.size:
        ws, hs = a.size.lower().split('x')
        w = int(ws) if ws else None
        h = int(hs) if hs else None
        if w and not h: h = round(im.height * w / im.width)
        if h and not w: w = round(im.width * h / im.height)
        im = im.resize((w, h), Image.LANCZOS)

    inks = SETS[a.colors]
    adjusted = tone_adjust(im, a.black_point, a.white_point)
    idx, pal = quantize(adjusted, inks)
    data, stride = pack(idx, inks)
    emit(a.name, im.width, im.height, stride, data, a.out)

    if a.preview:
        prev = np.array([pal[i] for i in idx.flatten()], dtype=np.uint8).reshape(idx.shape + (3,))
        Image.fromarray(prev).resize((im.width * 3, im.height * 3), Image.NEAREST).save(a.preview)
    print(f'{a.name}: {im.width}x{im.height}, stride {stride}, {len(data)} bytes, inks {inks}')


if __name__ == '__main__':
    main()